[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsonc"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "css"
language-servers = [ { name = "vscode-css-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "python"
auto-format = true

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "yamlfmt", args = [ "-formatter", "retain_line_breaks_single=true", "-" ] }

[language-server.rust-analyzer.config.check]
command = "clippy"
# extraArgs = ["--", "-W", "clippy::pedantic"]

[language-server.tinymist.config]
formatterMode = "typstyle"
previewFeature = "disable"

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

