[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typst"
auto-format = true
language-servers = ["tinymist"]

[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true

[[language]]
name = "toml"
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"
# extraArgs = ["--", "-W", "clippy::pedantic"]

[language-server.tinymist.config]
formatterMode = "typstyle"
previewFeature = "disable"

[language-server.ruff]
command = "ruff"
args = ["server"]

